<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>property_api_err</key>
        <language>en</language>
        <message>The {0} has encountered the following error: {1}</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>admin</sys_created_by>
        <sys_created_on>2023-05-09 08:32:54</sys_created_on>
        <sys_id>65013480b6f6a110b91ed24fc20c7db8</sys_id>
        <sys_mod_count>0</sys_mod_count>
        <sys_name>property_api_err</sys_name>
        <sys_package display_value="Performance Review App" source="x_398999_perform_0">3801f08071f6a1101823a1bee9ed2cdd</sys_package>
        <sys_policy/>
        <sys_scope display_value="Performance Review App">3801f08071f6a1101823a1bee9ed2cdd</sys_scope>
        <sys_update_name>sys_ui_message_65013480b6f6a110b91ed24fc20c7db8</sys_update_name>
        <sys_updated_by>admin</sys_updated_by>
        <sys_updated_on>2023-05-09 08:32:54</sys_updated_on>
    </sys_ui_message>
</record_update>
